---
sudo: false
language: ruby
cache: bundler
rvm:
  - 3.1.2
  - 3.0.4
  - 2.7.6
  - 2.6.10
  - 2.5.9
  - 2.4.10
  - 2.3.8
  - 2.2.10
  - 2.1.10
jdk:
  - openjdk8
  - openjdk11
before_install:
  - gem install bundler